version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/:/etc/nginx/ssl/
      - ./conf.d/:/etc/nginx/conf.d/
      - ./www/:/var/www/
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./www/:/var/www/
